#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLThuVien")]
	public partial class DataQLTVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTPHIEUMUONSACH(CTPHIEUMUONSACH instance);
    partial void UpdateCTPHIEUMUONSACH(CTPHIEUMUONSACH instance);
    partial void DeleteCTPHIEUMUONSACH(CTPHIEUMUONSACH instance);
    partial void InsertCTPHIEUTRASACH(CTPHIEUTRASACH instance);
    partial void UpdateCTPHIEUTRASACH(CTPHIEUTRASACH instance);
    partial void DeleteCTPHIEUTRASACH(CTPHIEUTRASACH instance);
    partial void InsertDOCGIA(DOCGIA instance);
    partial void UpdateDOCGIA(DOCGIA instance);
    partial void DeleteDOCGIA(DOCGIA instance);
    partial void InsertPHIEUMUONSACH(PHIEUMUONSACH instance);
    partial void UpdatePHIEUMUONSACH(PHIEUMUONSACH instance);
    partial void DeletePHIEUMUONSACH(PHIEUMUONSACH instance);
    partial void InsertPHIEUTRASACH(PHIEUTRASACH instance);
    partial void UpdatePHIEUTRASACH(PHIEUTRASACH instance);
    partial void DeletePHIEUTRASACH(PHIEUTRASACH instance);
    partial void InsertSACH(SACH instance);
    partial void UpdateSACH(SACH instance);
    partial void DeleteSACH(SACH instance);
    partial void InsertLOAIDG(LOAIDG instance);
    partial void UpdateLOAIDG(LOAIDG instance);
    partial void DeleteLOAIDG(LOAIDG instance);
    partial void InsertLOAISACH(LOAISACH instance);
    partial void UpdateLOAISACH(LOAISACH instance);
    partial void DeleteLOAISACH(LOAISACH instance);
    #endregion
		
		public DataQLTVDataContext() : 
				base(global::UI.Properties.Settings.Default.QLThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLTVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLTVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLTVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLTVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<CTPHIEUMUONSACH> CTPHIEUMUONSACHes
		{
			get
			{
				return this.GetTable<CTPHIEUMUONSACH>();
			}
		}
		
		public System.Data.Linq.Table<CTPHIEUTRASACH> CTPHIEUTRASACHes
		{
			get
			{
				return this.GetTable<CTPHIEUTRASACH>();
			}
		}
		
		public System.Data.Linq.Table<DOCGIA> DOCGIAs
		{
			get
			{
				return this.GetTable<DOCGIA>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUMUONSACH> PHIEUMUONSACHes
		{
			get
			{
				return this.GetTable<PHIEUMUONSACH>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTRASACH> PHIEUTRASACHes
		{
			get
			{
				return this.GetTable<PHIEUTRASACH>();
			}
		}
		
		public System.Data.Linq.Table<SACH> SACHes
		{
			get
			{
				return this.GetTable<SACH>();
			}
		}
		
		public System.Data.Linq.Table<vDGMuonSach> vDGMuonSaches
		{
			get
			{
				return this.GetTable<vDGMuonSach>();
			}
		}
		
		public System.Data.Linq.Table<vDGMuonSach2> vDGMuonSach2s
		{
			get
			{
				return this.GetTable<vDGMuonSach2>();
			}
		}
		
		public System.Data.Linq.Table<vPhieuSach> vPhieuSaches
		{
			get
			{
				return this.GetTable<vPhieuSach>();
			}
		}
		
		public System.Data.Linq.Table<vDocGia> vDocGias
		{
			get
			{
				return this.GetTable<vDocGia>();
			}
		}
		
		public System.Data.Linq.Table<vTraSach> vTraSaches
		{
			get
			{
				return this.GetTable<vTraSach>();
			}
		}
		
		public System.Data.Linq.Table<LOAIDG> LOAIDGs
		{
			get
			{
				return this.GetTable<LOAIDG>();
			}
		}
		
		public System.Data.Linq.Table<LOAISACH> LOAISACHes
		{
			get
			{
				return this.GetTable<LOAISACH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT
	{
		
		private int _id;
		
		private string _Name;
		
		private string _Username;
		
		private string _Password;
		
		public ACCOUNT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUMUONSACH")]
	public partial class CTPHIEUMUONSACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCTPMS;
		
		private string _MaMuonSach;
		
		private string _MaSach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTPMSChanging(string value);
    partial void OnMaCTPMSChanged();
    partial void OnMaMuonSachChanging(string value);
    partial void OnMaMuonSachChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    #endregion
		
		public CTPHIEUMUONSACH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTPMS", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCTPMS
		{
			get
			{
				return this._MaCTPMS;
			}
			set
			{
				if ((this._MaCTPMS != value))
				{
					this.OnMaCTPMSChanging(value);
					this.SendPropertyChanging();
					this._MaCTPMS = value;
					this.SendPropertyChanged("MaCTPMS");
					this.OnMaCTPMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuonSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaMuonSach
		{
			get
			{
				return this._MaMuonSach;
			}
			set
			{
				if ((this._MaMuonSach != value))
				{
					this.OnMaMuonSachChanging(value);
					this.SendPropertyChanging();
					this._MaMuonSach = value;
					this.SendPropertyChanged("MaMuonSach");
					this.OnMaMuonSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUTRASACH")]
	public partial class CTPHIEUTRASACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCTPTS;
		
		private string _MaTraSach;
		
		private string _MaSach;
		
		private int _SoNgayMuon;
		
		private int _TienPhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTPTSChanging(string value);
    partial void OnMaCTPTSChanged();
    partial void OnMaTraSachChanging(string value);
    partial void OnMaTraSachChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnSoNgayMuonChanging(int value);
    partial void OnSoNgayMuonChanged();
    partial void OnTienPhatChanging(int value);
    partial void OnTienPhatChanged();
    #endregion
		
		public CTPHIEUTRASACH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTPTS", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCTPTS
		{
			get
			{
				return this._MaCTPTS;
			}
			set
			{
				if ((this._MaCTPTS != value))
				{
					this.OnMaCTPTSChanging(value);
					this.SendPropertyChanging();
					this._MaCTPTS = value;
					this.SendPropertyChanged("MaCTPTS");
					this.OnMaCTPTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTraSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaTraSach
		{
			get
			{
				return this._MaTraSach;
			}
			set
			{
				if ((this._MaTraSach != value))
				{
					this.OnMaTraSachChanging(value);
					this.SendPropertyChanging();
					this._MaTraSach = value;
					this.SendPropertyChanged("MaTraSach");
					this.OnMaTraSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayMuon", DbType="Int NOT NULL")]
		public int SoNgayMuon
		{
			get
			{
				return this._SoNgayMuon;
			}
			set
			{
				if ((this._SoNgayMuon != value))
				{
					this.OnSoNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._SoNgayMuon = value;
					this.SendPropertyChanged("SoNgayMuon");
					this.OnSoNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienPhat", DbType="Int NOT NULL")]
		public int TienPhat
		{
			get
			{
				return this._TienPhat;
			}
			set
			{
				if ((this._TienPhat != value))
				{
					this.OnTienPhatChanging(value);
					this.SendPropertyChanging();
					this._TienPhat = value;
					this.SendPropertyChanged("TienPhat");
					this.OnTienPhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOCGIA")]
	public partial class DOCGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDG;
		
		private string _MaLoaiDG;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _Email;
		
		private System.DateTime _NgayLapThe;
		
		private int _SoSachMuon;
		
		private bool _TinhTrangTraTre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDGChanging(string value);
    partial void OnMaDGChanged();
    partial void OnMaLoaiDGChanging(string value);
    partial void OnMaLoaiDGChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgayLapTheChanging(System.DateTime value);
    partial void OnNgayLapTheChanged();
    partial void OnSoSachMuonChanging(int value);
    partial void OnSoSachMuonChanged();
    partial void OnTinhTrangTraTreChanging(bool value);
    partial void OnTinhTrangTraTreChanged();
    #endregion
		
		public DOCGIA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDG", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDG
		{
			get
			{
				return this._MaDG;
			}
			set
			{
				if ((this._MaDG != value))
				{
					this.OnMaDGChanging(value);
					this.SendPropertyChanging();
					this._MaDG = value;
					this.SendPropertyChanged("MaDG");
					this.OnMaDGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDG", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoaiDG
		{
			get
			{
				return this._MaLoaiDG;
			}
			set
			{
				if ((this._MaLoaiDG != value))
				{
					this.OnMaLoaiDGChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiDG = value;
					this.SendPropertyChanged("MaLoaiDG");
					this.OnMaLoaiDGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapThe", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLapThe
		{
			get
			{
				return this._NgayLapThe;
			}
			set
			{
				if ((this._NgayLapThe != value))
				{
					this.OnNgayLapTheChanging(value);
					this.SendPropertyChanging();
					this._NgayLapThe = value;
					this.SendPropertyChanged("NgayLapThe");
					this.OnNgayLapTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSachMuon", DbType="Int NOT NULL")]
		public int SoSachMuon
		{
			get
			{
				return this._SoSachMuon;
			}
			set
			{
				if ((this._SoSachMuon != value))
				{
					this.OnSoSachMuonChanging(value);
					this.SendPropertyChanging();
					this._SoSachMuon = value;
					this.SendPropertyChanged("SoSachMuon");
					this.OnSoSachMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangTraTre", DbType="Bit NOT NULL")]
		public bool TinhTrangTraTre
		{
			get
			{
				return this._TinhTrangTraTre;
			}
			set
			{
				if ((this._TinhTrangTraTre != value))
				{
					this.OnTinhTrangTraTreChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangTraTre = value;
					this.SendPropertyChanged("TinhTrangTraTre");
					this.OnTinhTrangTraTreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUMUONSACH")]
	public partial class PHIEUMUONSACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMuonSach;
		
		private string _MaDG;
		
		private System.DateTime _NgayMuon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMuonSachChanging(string value);
    partial void OnMaMuonSachChanged();
    partial void OnMaDGChanging(string value);
    partial void OnMaDGChanged();
    partial void OnNgayMuonChanging(System.DateTime value);
    partial void OnNgayMuonChanged();
    #endregion
		
		public PHIEUMUONSACH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuonSach", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMuonSach
		{
			get
			{
				return this._MaMuonSach;
			}
			set
			{
				if ((this._MaMuonSach != value))
				{
					this.OnMaMuonSachChanging(value);
					this.SendPropertyChanging();
					this._MaMuonSach = value;
					this.SendPropertyChanged("MaMuonSach");
					this.OnMaMuonSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDG", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaDG
		{
			get
			{
				return this._MaDG;
			}
			set
			{
				if ((this._MaDG != value))
				{
					this.OnMaDGChanging(value);
					this.SendPropertyChanging();
					this._MaDG = value;
					this.SendPropertyChanged("MaDG");
					this.OnMaDGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="DateTime NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTRASACH")]
	public partial class PHIEUTRASACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTraSach;
		
		private string _MaMuonSach;
		
		private string _NgayTra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTraSachChanging(string value);
    partial void OnMaTraSachChanged();
    partial void OnMaMuonSachChanging(string value);
    partial void OnMaMuonSachChanged();
    partial void OnNgayTraChanging(string value);
    partial void OnNgayTraChanged();
    #endregion
		
		public PHIEUTRASACH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTraSach", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTraSach
		{
			get
			{
				return this._MaTraSach;
			}
			set
			{
				if ((this._MaTraSach != value))
				{
					this.OnMaTraSachChanging(value);
					this.SendPropertyChanging();
					this._MaTraSach = value;
					this.SendPropertyChanged("MaTraSach");
					this.OnMaTraSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuonSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaMuonSach
		{
			get
			{
				return this._MaMuonSach;
			}
			set
			{
				if ((this._MaMuonSach != value))
				{
					this.OnMaMuonSachChanging(value);
					this.SendPropertyChanging();
					this._MaMuonSach = value;
					this.SendPropertyChanged("MaMuonSach");
					this.OnMaMuonSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SACH")]
	public partial class SACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSach;
		
		private string _MaLoaiSach;
		
		private string _MaTacGia;
		
		private string _TenSach;
		
		private System.DateTime _NgayNhap;
		
		private string _NhaXB;
		
		private string _NamXB;
		
		private int _GiaSach;
		
		private bool _TinhTrangMuon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnMaLoaiSachChanging(string value);
    partial void OnMaLoaiSachChanged();
    partial void OnMaTacGiaChanging(string value);
    partial void OnMaTacGiaChanged();
    partial void OnTenSachChanging(string value);
    partial void OnTenSachChanged();
    partial void OnNgayNhapChanging(System.DateTime value);
    partial void OnNgayNhapChanged();
    partial void OnNhaXBChanging(string value);
    partial void OnNhaXBChanged();
    partial void OnNamXBChanging(string value);
    partial void OnNamXBChanged();
    partial void OnGiaSachChanging(int value);
    partial void OnGiaSachChanged();
    partial void OnTinhTrangMuonChanging(bool value);
    partial void OnTinhTrangMuonChanged();
    #endregion
		
		public SACH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaLoaiSach
		{
			get
			{
				return this._MaLoaiSach;
			}
			set
			{
				if ((this._MaLoaiSach != value))
				{
					this.OnMaLoaiSachChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiSach = value;
					this.SendPropertyChanged("MaLoaiSach");
					this.OnMaLoaiSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTacGia", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaTacGia
		{
			get
			{
				return this._MaTacGia;
			}
			set
			{
				if ((this._MaTacGia != value))
				{
					this.OnMaTacGiaChanging(value);
					this.SendPropertyChanging();
					this._MaTacGia = value;
					this.SendPropertyChanged("MaTacGia");
					this.OnMaTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this.OnTenSachChanging(value);
					this.SendPropertyChanging();
					this._TenSach = value;
					this.SendPropertyChanged("TenSach");
					this.OnTenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime NOT NULL")]
		public System.DateTime NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXB", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string NhaXB
		{
			get
			{
				return this._NhaXB;
			}
			set
			{
				if ((this._NhaXB != value))
				{
					this.OnNhaXBChanging(value);
					this.SendPropertyChanging();
					this._NhaXB = value;
					this.SendPropertyChanged("NhaXB");
					this.OnNhaXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXB", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string NamXB
		{
			get
			{
				return this._NamXB;
			}
			set
			{
				if ((this._NamXB != value))
				{
					this.OnNamXBChanging(value);
					this.SendPropertyChanging();
					this._NamXB = value;
					this.SendPropertyChanged("NamXB");
					this.OnNamXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSach", DbType="Int NOT NULL")]
		public int GiaSach
		{
			get
			{
				return this._GiaSach;
			}
			set
			{
				if ((this._GiaSach != value))
				{
					this.OnGiaSachChanging(value);
					this.SendPropertyChanging();
					this._GiaSach = value;
					this.SendPropertyChanged("GiaSach");
					this.OnGiaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangMuon", DbType="Bit NOT NULL")]
		public bool TinhTrangMuon
		{
			get
			{
				return this._TinhTrangMuon;
			}
			set
			{
				if ((this._TinhTrangMuon != value))
				{
					this.OnTinhTrangMuonChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangMuon = value;
					this.SendPropertyChanged("TinhTrangMuon");
					this.OnTinhTrangMuonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vDGMuonSach")]
	public partial class vDGMuonSach
	{
		
		private string _MaDG;
		
		private string _HoTen;
		
		private System.DateTime _NgayMuon;
		
		private string _TenSach;
		
		private int _GiaSach;
		
		private bool _TinhTrangMuon;
		
		public vDGMuonSach()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDG", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaDG
		{
			get
			{
				return this._MaDG;
			}
			set
			{
				if ((this._MaDG != value))
				{
					this._MaDG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="DateTime NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this._NgayMuon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSach", DbType="Int NOT NULL")]
		public int GiaSach
		{
			get
			{
				return this._GiaSach;
			}
			set
			{
				if ((this._GiaSach != value))
				{
					this._GiaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangMuon", DbType="Bit NOT NULL")]
		public bool TinhTrangMuon
		{
			get
			{
				return this._TinhTrangMuon;
			}
			set
			{
				if ((this._TinhTrangMuon != value))
				{
					this._TinhTrangMuon = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vDGMuonSach2")]
	public partial class vDGMuonSach2
	{
		
		private string _MaDG;
		
		private string _HoTen;
		
		private string _MaMuonSach;
		
		private string _MaSach;
		
		private string _TenSach;
		
		private System.DateTime _NgayMuon;
		
		private bool _TinhTrangMuon;
		
		public vDGMuonSach2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDG", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaDG
		{
			get
			{
				return this._MaDG;
			}
			set
			{
				if ((this._MaDG != value))
				{
					this._MaDG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuonSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaMuonSach
		{
			get
			{
				return this._MaMuonSach;
			}
			set
			{
				if ((this._MaMuonSach != value))
				{
					this._MaMuonSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="DateTime NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this._NgayMuon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangMuon", DbType="Bit NOT NULL")]
		public bool TinhTrangMuon
		{
			get
			{
				return this._TinhTrangMuon;
			}
			set
			{
				if ((this._TinhTrangMuon != value))
				{
					this._TinhTrangMuon = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vPhieuSach")]
	public partial class vPhieuSach
	{
		
		private string _MaMuonSach;
		
		private string _MaCTPMS;
		
		private string _MaSach;
		
		private string _MaDG;
		
		private string _TenSach;
		
		private System.DateTime _NgayMuon;
		
		private bool _TinhTrangMuon;
		
		public vPhieuSach()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuonSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaMuonSach
		{
			get
			{
				return this._MaMuonSach;
			}
			set
			{
				if ((this._MaMuonSach != value))
				{
					this._MaMuonSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTPMS", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaCTPMS
		{
			get
			{
				return this._MaCTPMS;
			}
			set
			{
				if ((this._MaCTPMS != value))
				{
					this._MaCTPMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDG", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaDG
		{
			get
			{
				return this._MaDG;
			}
			set
			{
				if ((this._MaDG != value))
				{
					this._MaDG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="DateTime NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this._NgayMuon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangMuon", DbType="Bit NOT NULL")]
		public bool TinhTrangMuon
		{
			get
			{
				return this._TinhTrangMuon;
			}
			set
			{
				if ((this._TinhTrangMuon != value))
				{
					this._TinhTrangMuon = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vDocGia")]
	public partial class vDocGia
	{
		
		private string _MaDG;
		
		private string _MaLoaiDG;
		
		private string _LoaiDG;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _Email;
		
		private System.DateTime _NgayLapThe;
		
		private int _SoSachMuon;
		
		private bool _TinhTrangTraTre;
		
		public vDocGia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDG", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaDG
		{
			get
			{
				return this._MaDG;
			}
			set
			{
				if ((this._MaDG != value))
				{
					this._MaDG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDG", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaLoaiDG
		{
			get
			{
				return this._MaLoaiDG;
			}
			set
			{
				if ((this._MaLoaiDG != value))
				{
					this._MaLoaiDG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDG", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string LoaiDG
		{
			get
			{
				return this._LoaiDG;
			}
			set
			{
				if ((this._LoaiDG != value))
				{
					this._LoaiDG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapThe", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLapThe
		{
			get
			{
				return this._NgayLapThe;
			}
			set
			{
				if ((this._NgayLapThe != value))
				{
					this._NgayLapThe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSachMuon", DbType="Int NOT NULL")]
		public int SoSachMuon
		{
			get
			{
				return this._SoSachMuon;
			}
			set
			{
				if ((this._SoSachMuon != value))
				{
					this._SoSachMuon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangTraTre", DbType="Bit NOT NULL")]
		public bool TinhTrangTraTre
		{
			get
			{
				return this._TinhTrangTraTre;
			}
			set
			{
				if ((this._TinhTrangTraTre != value))
				{
					this._TinhTrangTraTre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTraSach")]
	public partial class vTraSach
	{
		
		private string _MaDG;
		
		private string _HoTen;
		
		private string _MaMuonSach;
		
		private string _MaTraSach;
		
		private string _MaCTPTS;
		
		private string _MaSach;
		
		private string _TenSach;
		
		private System.DateTime _NgayMuon;
		
		private string _NgayTra;
		
		private int _SoNgayMuon;
		
		private int _TienPhat;
		
		public vTraSach()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDG", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaDG
		{
			get
			{
				return this._MaDG;
			}
			set
			{
				if ((this._MaDG != value))
				{
					this._MaDG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuonSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaMuonSach
		{
			get
			{
				return this._MaMuonSach;
			}
			set
			{
				if ((this._MaMuonSach != value))
				{
					this._MaMuonSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTraSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaTraSach
		{
			get
			{
				return this._MaTraSach;
			}
			set
			{
				if ((this._MaTraSach != value))
				{
					this._MaTraSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTPTS", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaCTPTS
		{
			get
			{
				return this._MaCTPTS;
			}
			set
			{
				if ((this._MaCTPTS != value))
				{
					this._MaCTPTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="DateTime NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this._NgayMuon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this._NgayTra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayMuon", DbType="Int NOT NULL")]
		public int SoNgayMuon
		{
			get
			{
				return this._SoNgayMuon;
			}
			set
			{
				if ((this._SoNgayMuon != value))
				{
					this._SoNgayMuon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienPhat", DbType="Int NOT NULL")]
		public int TienPhat
		{
			get
			{
				return this._TienPhat;
			}
			set
			{
				if ((this._TienPhat != value))
				{
					this._TienPhat = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIDG")]
	public partial class LOAIDG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiDG;
		
		private string _LoaiDG1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiDGChanging(string value);
    partial void OnMaLoaiDGChanged();
    partial void OnLoaiDGChanging(string value);
    partial void OnLoaiDGChanged();
    #endregion
		
		public LOAIDG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDG", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiDG
		{
			get
			{
				return this._MaLoaiDG;
			}
			set
			{
				if ((this._MaLoaiDG != value))
				{
					this.OnMaLoaiDGChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiDG = value;
					this.SendPropertyChanged("MaLoaiDG");
					this.OnMaLoaiDGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDG1", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string LoaiDG
		{
			get
			{
				return this._LoaiDG1;
			}
			set
			{
				if ((this._LoaiDG1 != value))
				{
					this.OnLoaiDGChanging(value);
					this.SendPropertyChanging();
					this._LoaiDG1 = value;
					this.SendPropertyChanged("LoaiDG");
					this.OnLoaiDGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAISACH")]
	public partial class LOAISACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiSach;
		
		private string _LoaiSach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiSachChanging(string value);
    partial void OnMaLoaiSachChanged();
    partial void OnLoaiSachChanging(string value);
    partial void OnLoaiSachChanged();
    #endregion
		
		public LOAISACH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiSach", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiSach
		{
			get
			{
				return this._MaLoaiSach;
			}
			set
			{
				if ((this._MaLoaiSach != value))
				{
					this.OnMaLoaiSachChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiSach = value;
					this.SendPropertyChanged("MaLoaiSach");
					this.OnMaLoaiSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiSach", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiSach
		{
			get
			{
				return this._LoaiSach;
			}
			set
			{
				if ((this._LoaiSach != value))
				{
					this.OnLoaiSachChanging(value);
					this.SendPropertyChanging();
					this._LoaiSach = value;
					this.SendPropertyChanged("LoaiSach");
					this.OnLoaiSachChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
